apiVersion: v1
kind: Service
metadata:
  name: pet-foods-be-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: petbeport
    protocol: TCP
  selector:
    app: pet-foods-be
  type: NodePort